CREATE TABLE "FILE"
(
    ID      NUMBER        NOT NULL ENABLE,
    CONSTRAINT FILE_PK PRIMARY KEY (ID),
    NAME    NVARCHAR2(20) NOT NULL,
    FORMAT  NVARCHAR2(20) NOT NULL,
    "SIZE"  NUMBER        NOT NULL,
    STORAGE_ID NUMBER,
    FOREIGN KEY (STORAGE_ID) REFERENCES STORAGE (ID)
);